### ISSUE TITLE
As a user, I want to view the blog posts and use search functionality, so that users the search and view blogs based on their preference.

### ISSUE THREAD

**Issue by nithinsiddhartha** [bhargavieppagunta/TinyBlogger#11]
# Estimation of efforts:
   Low.

# Estimated time for completion:
   6 Days.

# Acceptance Criteria:
Can view trending posts which are viewed by more users and most recently added  blogs, and  also navigating through blog  posts using search bar or single click on specific topics, according to their preferences.

**Comment by bhargavieppagunta** [comment]
The tasks assigned for this user story are reviewed and completed successfully.
So, closing the user story.
