### ISSUE TITLE
As a user, I aim for a user-friendly frontend data setup to efficiently manage and access data, ensuring seamless navigation and enhancing overall user experience.

### ISSUE THREAD

**Issue by Sahithi3011** [bhargavieppagunta/TinyBlogger#13]
# Estimation of efforts: 
Moderate

# Estimated time for completion:  
1 week

# Acceptance Criteria: 
extraction pf posts, topics and user data with secure process where data can be extracted from the database

**Comment by bhargavieppagunta** [comment]
The tasks assigned for this user story are reviewed and completed successfully.
So, closing the user story.
