### ISSUE TITLE
As an developer, I want to create and design frontend pages, so that I can implement intuitive and user-friendly interface for both admins and users.

### ISSUE THREAD

**Issue by PranathiBRaju** [bhargavieppagunta/TinyBlogger#15]
# Estimation of efforts:
 Moderate

# Estimated time for completion: 
10 days

# Acceptance Criteria:
frontend pages like index, about, forgot password, single, about, registration/login are designed for user-friendly and seamless experience.

**Comment by bhargavieppagunta** [comment]
The tasks assigned for this user story are reviewed and completed successfully.
So, closing the user story.
